# SPDX-License-Identifier: BSD-2-Clause
# Contains configuration settings for linting Python.

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
force_sort_within_sections = true
line_length = 79
